name: cd
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    env:
      BINTRAY_API_KEY: ${{secrets.BINTRAY_API_KEY}}
      GITHUB_ACTOR: ${{github.actor}}
      GITHUB_PASSWORD: ${{secrets.GH_PASSWORD}}
      GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
    if: github.actor == github.event.repository.owner.login
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - run: |
          mkdir ~/.ssh
          echo "${{secrets.SSH_KEY}}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          mvn --batch-mode --settings .maven/settings.xml release:prepare release:perform -DreleaseVersion=${{github.event.inputs.version}} -DtagNameFormat=${{github.event.inputs.version}}
          git checkout ${{github.event.inputs.version}}
          mvn --activate-profiles deploy --settings .maven/settings.xml clean deploy -DaltDeploymentRepository=bintray::https://api.bintray.com/maven/tahaviev/maven/cli-maven-plugin/;publish=1
