name: ci
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{hashFiles('pom.xml')}}
          restore-keys: maven-
      - run: mvn verify
