name: site
on: workflow_dispatch
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      GITHUB_ACTOR: ${{github.actor}}
      GITHUB_PASSWORD: ${{secrets.GH_PASSWORD}}
    if: github.actor == github.event.repository.owner.login
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-java@v1.3.0
        with:
          java-version: 11
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: maven-${{hashFiles('pom.xml')}}
          restore-keys: maven-
      - run: mvn --settings .maven/settings.xml site-deploy
